runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /assets/css
  static_dir: assets/css

- url: /assets/img
  static_dir: assets/img

- url: /assets/js
  static_dir: assets/js

- url: /assets/fonts
  static_dir: assets/fonts

- url: /bootstrap
  static_dir: bootstrap

- url: /trumbowyg
  static_dir: trumbowyg

- url: /login(/.*)*
  script: scripts.main.app
  login: required
  secure: always

- url: /.*
  script: scripts.main.app
  login: required
  secure: always
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: ssl
  version: latest
# [END libraries]
